version: "3.9"
services:
  mysql:
    image: mysql:8.0.33-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: